export default {
    loginTopText: 'VENDER LOG IN',
    loginUserNamePlaceholderText: 'Insert User Name (User or email)',
    loginPasswordPlaceholderText: 'Insert Password',
    userName: 'userName',
    password: 'password',
    loginUserNameValidation: 'Please Enter User Name',
    loginPasswordValidation: 'Please Enter Password',
    loginUserNameAndPasswordValidation: 'Please Enter User Name and Password',
    forgetPassword: 'Forget Password ?',
    logIn: 'LOG IN',
    functionScreenHeading: "FUNCTIONALITY SETTINGS",
    up: 'UP',
    down: 'DOWN',
    printerAndCash: 'PRINTERS & CASH DRAWER',
    cardReader: 'CARD READER',
    funcSetting: 'FUNCTIONALITIES SETTINGS',
    deviceSetting: "DEVICE SETTINGS",
}